// ─────────────────────────────────────────────────────────────────────────────
// Spinative — Shared asset type definitions
// ─────────────────────────────────────────────────────────────────────────────

/** Rich project context from the Theme panel — fed directly into AI prompts */
export interface ProjectMeta {
  /** Game title (e.g. "Lucky Bull") */
  gameName?:       string
  /** Theme key (e.g. "western") */
  themeKey?:       string
  /** Setting / World free-text */
  setting?:        string
  /** Narrative arc free-text */
  story?:          string
  /** Mood / Tone selection */
  mood?:           string
  /** Bonus Round Narrative */
  bonusNarrative?: string
  /** Art Style selection. New projects set a styleId token here
   *  ("realistic_3d") that resolves via GRAPHIC_STYLES. Legacy projects
   *  set a free-text label ("Realistic") which promptBuilder maps through
   *  legacyStyleToId on the server. */
  artStyle?:       string
  /** Canonical style token (GRAPHIC_STYLES id). Preferred over artStyle
   *  when both are present. */
  styleId?:        string
  /** Visual Inspiration / Art Reference — free text. */
  artRef?:         string
  /** Uploaded reference images + their GPT-4o-generated STYLE descriptions.
   *  The image URLs go to Supabase Storage (CDN URLs) so the payload
   *  stays small. The description is what actually gets injected into
   *  the prompt at generation time — the image bytes aren't seen by
   *  gpt-image-1 (it's a text-to-image API). See
   *  /api/references/describe for how descriptions are produced.
   *  Capped at 3 entries by the UI; the builder iterates whatever is
   *  present, so ignore-or-include is free server-side. */
  artRefImages?:   Array<{
    id:          string
    url:         string
    description: string
  }>
  /** The project's "art bible" — a single locked-in visual signature
   *  (palette, material treatment, lighting language, ornament density,
   *  line work) that gets injected into EVERY prompt as a high-priority
   *  context line. Solves the cross-asset cohesion problem: even with
   *  the same style + theme + palette + references, separate generation
   *  calls drift because the image model doesn't know what the
   *  project's prior assets actually look like. Generated by running
   *  /api/references/describe with kind:'art_bible' over an anchor asset
   *  the user has already approved (logo / character / background_base /
   *  any uploaded asset).  Editable — once generated the user can tweak
   *  the description before it locks in. */
  artBible?: {
    /** The anchor asset key the description was derived from (e.g.
     *  'logo', 'character', 'background_base', or a custom upload key).
     *  Stored so the panel can show "generated from <type>" and offer
     *  a one-click "regenerate from same anchor" action. */
    anchorAssetKey?: string
    /** CDN URL of the anchor image at the time of generation. Kept for
     *  thumbnail rendering even if the underlying asset is later
     *  re-generated; the bible should NOT auto-update when its anchor
     *  changes (that's a manual user action). */
    anchorUrl?:      string
    /** The vision-describe output. ~120 words. This is what actually
     *  gets injected into prompts. Free-text — the user can edit. */
    description:    string
    /** ISO timestamp — when the description was generated. Shown as
     *  "locked 2 hours ago" in the panel. */
    generatedAt:    string
  }
  /** Art Direction Notes */
  artNotes?:       string
  /** Colour palette primary */
  colorPrimary?:   string
  /** Colour palette background */
  colorBg?:        string
  /** Colour palette accent */
  colorAccent?:    string
  /** Whether the matching colour is "active" — when false the prompt
   *  builder skips that tone entirely (it's not just hidden from the
   *  palette UI). Defaults to true when unset so older payloads with
   *  the three hexes but no toggle bits still behave. */
  colorPrimaryOn?: boolean
  colorBgOn?:      boolean
  colorAccentOn?:  boolean
  /** Symbol counts */
  symbolHighCount?:    number
  symbolLowCount?:     number
  symbolSpecialCount?: number
  /** Per-symbol names (from the Symbols panel) */
  symbolHighNames?:    string[]
  symbolLowNames?:     string[]
  symbolSpecialNames?: string[]
}

export type AssetType =
  | 'background_base'
  | 'background_bonus'
  // High symbols — up to 8
  | 'symbol_high_1'
  | 'symbol_high_2'
  | 'symbol_high_3'
  | 'symbol_high_4'
  | 'symbol_high_5'
  | 'symbol_high_6'
  | 'symbol_high_7'
  | 'symbol_high_8'
  // Low symbols — up to 8
  | 'symbol_low_1'
  | 'symbol_low_2'
  | 'symbol_low_3'
  | 'symbol_low_4'
  | 'symbol_low_5'
  | 'symbol_low_6'
  | 'symbol_low_7'
  | 'symbol_low_8'
  // Special symbols — named first two + up to 6 additional
  | 'symbol_wild'
  | 'symbol_scatter'
  | 'symbol_special_3'
  | 'symbol_special_4'
  | 'symbol_special_5'
  | 'symbol_special_6'
  | 'logo'
  | 'character'
  | 'reel_frame'
  | 'spin_button'
  | 'jackpot_label'

export const ASSET_TYPES: AssetType[] = [
  'background_base',
  'background_bonus',
  'symbol_high_1', 'symbol_high_2', 'symbol_high_3', 'symbol_high_4',
  'symbol_high_5', 'symbol_high_6', 'symbol_high_7', 'symbol_high_8',
  'symbol_low_1',  'symbol_low_2',  'symbol_low_3',  'symbol_low_4',
  'symbol_low_5',  'symbol_low_6',  'symbol_low_7',  'symbol_low_8',
  'symbol_wild', 'symbol_scatter',
  'symbol_special_3', 'symbol_special_4', 'symbol_special_5', 'symbol_special_6',
  'logo',
  'character',
  'reel_frame',
  'spin_button',
  'jackpot_label',
]

export const ASSET_LABELS: Record<AssetType, string> = {
  background_base:   'Background — Base Game',
  background_bonus:  'Background — Bonus/Free Spins',
  symbol_high_1:     'High 1',
  symbol_high_2:     'High 2',
  symbol_high_3:     'High 3',
  symbol_high_4:     'High 4',
  symbol_high_5:     'High 5',
  symbol_high_6:     'High 6',
  symbol_high_7:     'High 7',
  symbol_high_8:     'High 8',
  symbol_low_1:      'Low 1',
  symbol_low_2:      'Low 2',
  symbol_low_3:      'Low 3',
  symbol_low_4:      'Low 4',
  symbol_low_5:      'Low 5',
  symbol_low_6:      'Low 6',
  symbol_low_7:      'Low 7',
  symbol_low_8:      'Low 8',
  symbol_wild:       'Wild',
  symbol_scatter:    'Scatter',
  symbol_special_3:  'Special 3',
  symbol_special_4:  'Special 4',
  symbol_special_5:  'Special 5',
  symbol_special_6:  'Special 6',
  logo:              'Game Logo',
  character:         'Character',
  reel_frame:        'Reel Frame',
  spin_button:       'Spin Button',
  jackpot_label:     'Jackpot Label',
}

// ─── Generated asset record (what we store in DB) ───────────────────────────

export interface GeneratedAsset {
  id:         string
  project_id: string
  type:       AssetType
  url:        string
  prompt:     string
  theme:      string
  provider:   'runway' | 'openai' | 'mock' | 'upload'
  created_at: string
}

// ─── Generation pipeline results ────────────────────────────────────────────

export interface GenerationResult {
  backgrounds: {
    base:  GeneratedAsset
    bonus: GeneratedAsset
  }
  symbols: {
    high:    GeneratedAsset[]   // length 5
    low:     GeneratedAsset[]   // length 5
    wild:    GeneratedAsset
    scatter: GeneratedAsset
  }
  logo: GeneratedAsset
}

// ─── Aspect ratio ────────────────────────────────────────────────────────────
// User-selectable output aspect ratio. Each provider is mapped to its nearest
// supported size in lib/ai/index.ts. When the caller does not specify a ratio
// we fall back to DEFAULT_RATIO_FOR_ASSET (also in lib/ai/index.ts) — which
// encodes the natural aspect per asset type (symbols 1:1, logo 3:1, etc.).
export type AspectRatio =
  | '1:1'     // square — symbols, UI buttons, jackpot tier badges
  | '3:2'     // classic background landscape
  | '2:3'     // portrait — characters, tall overlays
  | '16:9'    // wide banner — backgrounds in widescreen
  | '9:16'    // vertical banner — mobile portrait
  | '3:1'     // title banner — logo, intro/outro banners
  | '4:1'     // extra-wide banner — HUD / footer rows
  | '1:4'     // extra-tall column — expanded reel overlay

// ─── Generation request ──────────────────────────────────────────────────────

export interface GenerateRequest {
  theme:        string      // user's raw prompt e.g. "ancient egypt"
  project_id:   string
  provider?:    'runway' | 'openai' | 'auto'
  style_id?:    string      // graphic style ID from GRAPHIC_STYLES (e.g. 'cartoon_3d')
  project_meta?: ProjectMeta
  /** When set, only generate these specific types (used for "fill gaps" mode). */
  asset_types?: AssetType[]
  /** Optional per-asset ratio override. Bulk calls apply this to every
   *  asset unless the asset type has its own default. */
  ratio?:       AspectRatio
  /** Per-slot prompt overrides (keyed on asset_type / feature slot key).
   *  When a type has an entry here, the pipeline substitutes the value
   *  for the composed prompt before calling the provider. Empty / missing
   *  entries fall through to normal composition. */
  custom_prompts?: Record<string, string>
}

export interface GenerateResponse {
  success: boolean
  result?: GenerationResult
  error?:  string
  // Per-asset errors if some succeeded and some failed
  partial?: Partial<GenerationResult>
  failed?:  Array<{ type: AssetType; error: string }>
}

// ─── Canvas layer (Fabric.js compatible) ────────────────────────────────────

export interface CanvasLayer {
  id:       string
  type:     AssetType
  label:    string
  url:      string
  visible:  boolean
  locked:   boolean
  // Fabric.js object properties
  left:     number
  top:      number
  scaleX:   number
  scaleY:   number
  angle:    number
  opacity:  number
  zIndex:   number
}

export interface CanvasState {
  layers:    CanvasLayer[]
  width:     number
  height:    number
  theme:     string
  projectId: string
}

// ─── Prompt builder types ────────────────────────────────────────────────────

export type PromptCategory =
  | 'background'
  | 'symbol_high'
  | 'symbol_low'
  | 'symbol_wild'
  | 'symbol_scatter'
  | 'logo'
  | 'character'
  | 'reel_frame'
  | 'spin_button'
  | 'jackpot_label'

/** Structured breakdown of a composed prompt, returned alongside the
 *  concatenated string. Enables the Single popup to display the hierarchy
 *  the model is receiving and lets the user see what each layer contributes
 *  before overriding via custom_prompt. */
export interface PromptSections {
  identity:        string   // style + theme (game name omitted for bg)
  template:        string   // category base (slot symbol / background / etc)
  context:         string[] // one entry per meta-derived line (mood, palette, world, …)
  differentiator:  string[] // tier / suit / "depicted as:" lines
  quality: {
    readability:   string
    consistency:   string
    core:          string
  }
  negatives: {
    universal:     string   // NEG_UNIVERSAL
    framing:       string   // NEG_ISOLATED or NEG_ENVIRONMENT
    extra:         string   // NEG_SYMBOLS (isolated) or NEG_SCENE_TEXT (env)
    style:         string   // style.negativeModifier, if any
  }
}

export interface BuiltPrompt {
  category: PromptCategory
  assetType: AssetType
  prompt:   string
  negativePrompt: string
  /** Structured view of the same prompt, used by the popup's
   *  "Prompt composition" section and the /preview endpoint. */
  sections?: PromptSections
}
